# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BluePrint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, blue_print: int=None):  # noqa: E501
        """BluePrint - a model defined in Swagger

        :param blue_print: The blue_print of this BluePrint.  # noqa: E501
        :type blue_print: int
        """
        self.swagger_types = {
            'blue_print': int
        }

        self.attribute_map = {
            'blue_print': 'bluePrint'
        }

        self._blue_print = blue_print

    @classmethod
    def from_dict(cls, dikt) -> 'BluePrint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bluePrint of this BluePrint.  # noqa: E501
        :rtype: BluePrint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def blue_print(self) -> int:
        """Gets the blue_print of this BluePrint.


        :return: The blue_print of this BluePrint.
        :rtype: int
        """
        return self._blue_print

    @blue_print.setter
    def blue_print(self, blue_print: int):
        """Sets the blue_print of this BluePrint.


        :param blue_print: The blue_print of this BluePrint.
        :type blue_print: int
        """
        if blue_print is not None and blue_print > 19:  # noqa: E501
            raise ValueError("Invalid value for `blue_print`, must be a value less than or equal to `19`")  # noqa: E501
        if blue_print is not None and blue_print < 1:  # noqa: E501
            raise ValueError("Invalid value for `blue_print`, must be a value greater than or equal to `1`")  # noqa: E501

        self._blue_print = blue_print
