# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LensStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, lens_status: bool=None):  # noqa: E501
        """LensStatus - a model defined in Swagger

        :param lens_status: The lens_status of this LensStatus.  # noqa: E501
        :type lens_status: bool
        """
        self.swagger_types = {
            'lens_status': bool
        }

        self.attribute_map = {
            'lens_status': 'lensStatus'
        }

        self._lens_status = lens_status

    @classmethod
    def from_dict(cls, dikt) -> 'LensStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The lensStatus of this LensStatus.  # noqa: E501
        :rtype: LensStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lens_status(self) -> bool:
        """Gets the lens_status of this LensStatus.


        :return: The lens_status of this LensStatus.
        :rtype: bool
        """
        return self._lens_status

    @lens_status.setter
    def lens_status(self, lens_status: bool):
        """Sets the lens_status of this LensStatus.


        :param lens_status: The lens_status of this LensStatus.
        :type lens_status: bool
        """

        self._lens_status = lens_status
