# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VideoStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, video_status: bool=None):  # noqa: E501
        """VideoStatus - a model defined in Swagger

        :param video_status: The video_status of this VideoStatus.  # noqa: E501
        :type video_status: bool
        """
        self.swagger_types = {
            'video_status': bool
        }

        self.attribute_map = {
            'video_status': 'videoStatus'
        }

        self._video_status = video_status

    @classmethod
    def from_dict(cls, dikt) -> 'VideoStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The videoStatus of this VideoStatus.  # noqa: E501
        :rtype: VideoStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def video_status(self) -> bool:
        """Gets the video_status of this VideoStatus.


        :return: The video_status of this VideoStatus.
        :rtype: bool
        """
        return self._video_status

    @video_status.setter
    def video_status(self, video_status: bool):
        """Sets the video_status of this VideoStatus.


        :param video_status: The video_status of this VideoStatus.
        :type video_status: bool
        """

        self._video_status = video_status
